# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4656abb81a4b3f7272563ab84309dcf00962f4f937427da92936ddc062b05f2b04daa1ec60ffbf2bd5b1b3a3ea9c309b2a7b34597f4cfed3c2654bb871c677f0

test:
  secret_key_base: 7dac7a3a5e64e9de1f49ed90d8b5c95c4b2ceaeaf11b1e81b16a2045e89189677fb8d86b84c9deebde78f6a20011388ff946dc2767a443b1e09ff32cad1e204e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
